[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

# [lib]
# name = 'lib'
# path = "./src/lib.rs"
#
# [errors]
# name = 'errors'
# path = "./src/errors.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
